#!/bin/sh
# Sikuli settings presets
DEBUG=1
# other Java settings
JAVA=X
PROPS='-Xmx512M -Dfile.encoding=UTF-8'

usage()
{
cat << EOF
usage: $0 options
OPTIONS:
           () = default 
   -h      Show this message
   -d n    n = debug level (1)
   -f      logs to SikuliLog.txt in working dir
   -u      user logs go to UserLog.txt in working dir
   -j n    n = Java version 6, 7, o (current active version)
   
you must specify one of the following options   
   -r xxx  run this Sikuli script xxx: some.sikuli (abs / rel path)
   -i      start interactive session (default if no options)
   
if you want to pass something to your script
   --      ends the command script option list - trailing stuff goes to sys.argv
           a string not starting with a hyphen does the same and is passed too
--------------------------------------------------------------------------------   
EOF
}

while getopts “:hj:d:fuir:” OPTION
do
  case $OPTION in
    h)
       usage
       exit 1
       ;;
    j)
       JAVA=$OPTARG
       ;;
    d)
       DEBUG=$OPTARG
       ;;
    f)
       PROPS="$PROPS -Dsikuli.Logfile"
       ;;
    u)
       PROPS="$PROPS -Dsikuli.LogfileUser"
       ;;
    i)
       ARGS=-i
       ;;
    r)
       ARGS="-r $OPTARG"
       ;;
    ?)
       usage
       exit 1
       ;;
    :)
       usage
       exit 1
       ;;
  esac
done

shift $((OPTIND-1))

if [ "$ARGS" == ""  ]; then
   usage
   exit 1
fi

if [ "$JAVA" != "X" ]; then
  echo "being asked to switch to Java "$JAVA
  if [ "$JAVA" = "6" ]; then
    echo trying Java 6
    export JAVA_HOME=`/usr/libexec/java_home -v 1.6`
  elif [ "$JAVA" = "o" ]; then
    if [ -e /Library/Java/JavaVirtualMachines/1.7.0u.jdk/Contents/Home ]; then
      echo trying OpenJDK 7
      export JAVA_HOME=/Library/Java/JavaVirtualMachines/1.7.0u.jdk/Contents/Home
    fi
  elif [ "$JAVA" = "7" ]; then
    echo trying Java 7
    export JAVA_HOME=`/usr/libexec/java_home -v 1.7`
  fi
fi

if [ "$SIKULI_HOME" == "" ]; then
  echo no SIKULI_HOME in environment
  if [ -e "`pwd`/SikuliX" ]; then
    export SIKULI_HOME=`pwd`/SikuliX
  else
    export SIKULI_HOME=`pwd`
  fi 
fi

if [ -e "$SIKULI_HOME/libs/libVisionProxy.dylib" ]; then
  echo SIKULI_HOME is $SIKULI_HOME
  echo seems to be valid - trying to start Sikuli Script
  echo "running with: $PROPS -Dsikuli.Debug=$DEBUG"
  echo "-jar $SIKULI_HOME/sikuli-script.jar $ARGS $@"
  java $PROPS -Dsikuli.Debug=$DEBUG -jar $SIKULI_HOME/sikuli-script.jar $ARGS $@
else
  echo SIKULI_HOME seems to be invalid \( $SIKULI_HOME \)
fi
