#!/bin/sh
# Sikuli settings presets
DEBUG=1
CONSOLE="-Dsikuli.console=true"
# other Java settings
JAVA=X
PROPS='-Xmx512M -Dapple.laf.useScreenMenuBar -Dfile.encoding=UTF-8'

usage()
{
cat << EOF
usage: $0 options
OPTIONS:
           () = default
   -h      Show this message
   -d n    n = debug level (1)
   -j n    n = Java version 6, 7, o (current active version)
   -f      logs to SikuliLog.txt in working dir
   -u      user logs go to UserLog.txt in working dir
   -c      all output goes to command window synchonously (IDE message area)

	if you want to store something in sys.argv for later script runs
   --      ends the command script option list - trailing stuff goes to sys.argv
           a string not starting with a hyphen does the same and is passed too
   
(the deprecated options -r -t -s are not supported by this command script)
--------------------------------------------------------------------------------   
EOF
}

while getopts “:hd:j:fuc” OPTION
do
  case $OPTION in
    h)
       usage
       exit 1
       ;;
    d)
       DEBUG=$OPTARG
       ;;
    j)
       JAVA=$OPTARG
       ;;
    f)
       PROPS="$PROPS -Dsikuli.Logfile"
       ;;
    u)
       PROPS="$PROPS -Dsikuli.LogfileUser"
       ;;
    c)
       CONSOLE="-Dsikuli.console=false"
       ;;
    ?)
       usage
       exit 1
       ;;
    :)
       usage
       exit 1
       ;;
  esac
done

shift $((OPTIND-1))

if [ "$JAVA" != "X" ]; then
  echo "being asked to switch to Java "$JAVA
  if [ "$JAVA" = "6" ]; then
    echo trying Java 6
    export JAVA_HOME=`/usr/libexec/java_home -v 1.6`
  elif [ "$JAVA" = "o" ]; then
    if [ -e /Library/Java/JavaVirtualMachines/1.7.0u.jdk/Contents/Home ]; then
      echo trying OpenJDK 7
      export JAVA_HOME=/Library/Java/JavaVirtualMachines/1.7.0u.jdk/Contents/Home
    fi
  elif [ "$JAVA" = "7" ]; then
    echo trying Java 7
    export JAVA_HOME=`/usr/libexec/java_home -v 1.7`
  fi
fi

if [ "$SIKULI_HOME" == "" ]; then
  echo no SIKULI_HOME
  if [ -e "`pwd`/SikuliX" ]; then
    export SIKULI_HOME=`pwd`/SikuliX
  else
    export SIKULI_HOME=`pwd`
  fi
fi

if [ -e "$SIKULI_HOME/libs/libVisionProxy.dylib" ]; then
  echo SIKULI_HOME is $SIKULI_HOME
  echo seems to be valid - trying to start Sikuli IDE
  echo "running $PROPS $CONSOLE -Dsikuli.Debug=$DEBUG"
  echo "-jar $SIKULI_HOME/sikuli-ide.jar $*"
  java $PROPS $CONSOLE -Dsikuli.Debug=$DEBUG -jar $SIKULI_HOME/sikuli-ide.jar $@
else
  echo SIKULI_HOME seems to be invalid \( $SIKULI_HOME \)
fi
  
