#!/bin/sh
# javac -cp classpath -sourcepath spath -d path-classes -source 1.6 target 1.6

export JAVA_HOME=/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
echo ---java_home--- 
echo $JAVA_HOME
echo --- java version ---
java -version
echo --- javac version ---
javac -version

runbase=`pwd`
echo --- running in ---
echo $runbase

srcbase=$runbase/../Script-Java
echo --- source from ---
echo $srcbase

tgtbase=$runbase/build/Mac
cfiles=sclasses6
echo --- class files ---
echo $tgtbase/$cfiles
mkdir $tgtbase/$cfiles 

cpb=$runbase/lib
clp=$tgtbase/$cfiles
clp=$clp:$cpb/commons-cli-1.2.jar
clp=$clp:$cpb/jintellitype-1.3.6.jar
clp=$clp:$cpb/JXGrabKey.jar
clp=$clp:/Volumes/RaiManStuff/51_Sikuli2012/RaiManSikuli2012-Script/jython-2.5.3.jar 
echo --- class path ---
echo $clp

echo --- command ---
sb=$srcbase
cmd="javac -classpath $clp -sourcepath $srcbase -d $tgtbase/$cfiles"
$cmd $sb/org/sikuli/script/*.java 
$cmd $sb/org/sikuli/system/*.java
$cmd $sb/org/sikuli/utility/*.java

