#!/bin/sh
if [ "$1" = "6" ]; then
  echo switching to java 6
  export JAVA_HOME=/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/
elif [ "$1" = "o" ]; then
  echo switching to OpenJDK 7
  export JAVA_HOME=/Users/rhocke/Documents/openjdkRaiMan/jdk1.7.0.jdk/Contents/Home/
else
  echo switching to java 7
  export JAVA_HOME=`/usr/libexec/java_home`
fi 
java -version
ant -f build-mac-app.xml
